#!/bin/bash


../bin/solve_all_subgames ms2f1t1h5_params none_params none_params mb1b1_params mb1b1_params cfrps_params cfrps2_params 1 200 200 unsafe cbrs card zerosum avg none mem 8
../bin/assemble_subgames ms2f1t1h5_params none_params none_params none_params mb1b1_params mb1b1_params cfrps_params cfrps2_params cfrpsmu2_params 1 200 200 unsafe
# Expect 13.77.  Or 14.10 without --fast-math.
../bin/run_rgbr ms2f1t1h5_params none_params mb1b1_params cfrpsmu2_params 1 200 avg raw
